<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vobi_fce"
 *
 * Auto generated by Extension Builder 2014-07-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Flexible content elements',
	'description' => '',
	'category' => 'templates',
	'author' => 'Robert Ferencek',
	'author_email' => 'robert@vobi.si',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);